server:
  port: 8082
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-password: 12345678
    key-store-type: PKCS12

spring:
  profiles:
    include:
      - oauth
      - real-db
  session:
    store-type: jdbc

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
